# Generated by Django 5.2.1 on 2025-06-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aulas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('aula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nivel', to='aulas.aula')),
            ],
            options={
                'db_table': 'nivel',
            },
        ),
    ]
