# Generated by Django 5.2.1 on 2025-06-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_culminacion', models.DateField()),
            ],
            options={
                'db_table': 'gestion',
            },
        ),
    ]
