services:
  web:
    build: ./aula-inteligente-back/
    container_name: django_backend
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=DB_aula_parcial_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=071104
      - CORS_ALLOWED_ORIGINS=http://localhost:4000,http://angular-app:4000
    volumes:
      - ./aula-inteligente-back:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    networks:
      - backend
      - frontend


networks:
  backend:
    external: true
  frontend:
    driver: bridge
