# Generated by Django 5.2.1 on 2025-06-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niveles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('carga_horaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=30)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='niveles.nivel')),
            ],
            options={
                'db_table': 'materia',
            },
        ),
    ]
