# Generated by Django 5.2.1 on 2025-06-03 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '__first__'),
        ('materias', '0001_initial'),
        ('trimestre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('poderacion', models.FloatField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='estudiantes.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='materias.materia')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='trimestre.trimestre')),
            ],
            options={
                'db_table': 'evaluacion',
            },
        ),
    ]
