# Generated by Django 5.2.1 on 2025-06-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'aula',
            },
        ),
    ]
