# Generated by Django 5.2.1 on 2025-06-03 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('materias', '0001_initial'),
        ('trimestre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletinMateria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ser', models.FloatField(blank=True, null=True)),
                ('saber', models.FloatField(blank=True, null=True)),
                ('hacer', models.FloatField(blank=True, null=True)),
                ('decidir', models.FloatField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletin_materias', to='estudiantes.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletin_materias', to='materias.materia')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletin_materias', to='trimestre.trimestre')),
            ],
            options={
                'db_table': 'boletin_materia',
            },
        ),
    ]
