# Generated by Django 5.2.1 on 2025-06-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestiones', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_culminacion', models.DateField()),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='gestiones.gestion')),
            ],
            options={
                'db_table': 'trimestre',
            },
        ),
    ]
