# Generated by Django 5.2.1 on 2025-06-03 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '0001_initial'),
        ('gestiones', '0001_initial'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_docente', to='docentes.docente')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_docente', to='gestiones.gestion')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_docente', to='materias.materia')),
            ],
            options={
                'db_table': 'asignacion_docente',
            },
        ),
    ]
