# Generated by Django 5.2.1 on 2025-06-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=30)),
                ('duracion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=30)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='materias.materia')),
            ],
            options={
                'db_table': 'tema',
            },
        ),
    ]
