# Generated by Django 5.2.1 on 2025-06-03 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestiones', '0001_initial'),
        ('niveles', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('carnet_estudiante', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('rude', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=30)),
                ('telefono_apoderado', models.CharField(max_length=50)),
                ('nombre_apoderado', models.CharField(max_length=255)),
                ('apellido_apoderado', models.CharField(max_length=255)),
                ('carnet_apoderado', models.CharField(max_length=20)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='gestiones.gestion')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='niveles.nivel')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
    ]
