# Generated by Django 5.2.1 on 2025-06-03 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('carnet', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('especialidad', models.CharField(max_length=255)),
                ('fecha_contratacion', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'docente',
            },
        ),
    ]
